apiVersion: v1
kind: Service
metadata:
  name: express-app-service
  namespace: secure-flight
spec:
  selector:
    app: express-app
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8081
