apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: secure-flight
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
        - name: mysql-config
          configMap:
            name: mysql-config
        - name: mysql-init-script
          configMap:
            name: mysql-init-script
      containers:
        - name: mysql
          image: mysql:5.6
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "root"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-config
              mountPath: /etc/mysql/mysql.conf.d
            - name: mysql-init-script
              mountPath: /docker-entrypoint-initdb.d
              readOnly: true
